services:
  zabbix-proxy:
    image: zabbix/zabbix-proxy-sqlite3:ubuntu-7.0-latest
    container_name: zabbix-proxy
    restart: always
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix_proxy_db:/var/lib/zabbix/db_data:rw
      - ./zabbix_proxy.psk:/var/lib/zabbix/zabbix_proxy.psk:ro
    env_file:
      - .env

  zabbix-agent2:
    image: zabbix/zabbix-agent2:ubuntu-latest
    container_name: zabbix-agent2
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
